// Auto-generated static enum constants from Waldur SDK
// This file provides all enum constants as static imports for better IDE support

// ===== EVENT ENUMS =====

export const Access_subnetsEnum = {
  access_subnet_creation_succeeded: 'access_subnet_creation_succeeded',
  access_subnet_deletion_succeeded: 'access_subnet_deletion_succeeded',
  access_subnet_update_succeeded: 'access_subnet_update_succeeded',
} as const;

export const AuthEnum = {
  auth_logged_in_with_username: 'auth_logged_in_with_username',
  auth_logged_out: 'auth_logged_out',
  auth_login_failed_with_username: 'auth_login_failed_with_username',
  token_created: 'token_created',
  token_lifetime_updated: 'token_lifetime_updated',
} as const;

export const CallEnum = {
  call_document_added: 'call_document_added',
  call_document_removed: 'call_document_removed',
} as const;

export const CreditsEnum = {
  allowed_offerings_have_been_updated: 'allowed_offerings_have_been_updated',
  automatic_credit_adjustment: 'automatic_credit_adjustment',
  create_of_credit_by_staff: 'create_of_credit_by_staff',
  reduction_of_customer_credit: 'reduction_of_customer_credit',
  reduction_of_customer_credit_due_to_minimal_consumption: 'reduction_of_customer_credit_due_to_minimal_consumption',
  reduction_of_customer_expected_consumption: 'reduction_of_customer_expected_consumption',
  reduction_of_project_credit: 'reduction_of_project_credit',
  reduction_of_project_credit_due_to_minimal_consumption: 'reduction_of_project_credit_due_to_minimal_consumption',
  reduction_of_project_expected_consumption: 'reduction_of_project_expected_consumption',
  roll_back_customer_credit: 'roll_back_customer_credit',
  roll_back_project_credit: 'roll_back_project_credit',
  set_to_zero_overdue_credit: 'set_to_zero_overdue_credit',
  update_of_credit_by_staff: 'update_of_credit_by_staff',
} as const;

export const CustomersEnum = {
  allowed_offerings_have_been_updated: 'allowed_offerings_have_been_updated',
  automatic_credit_adjustment: 'automatic_credit_adjustment',
  create_of_credit_by_staff: 'create_of_credit_by_staff',
  customer_creation_succeeded: 'customer_creation_succeeded',
  customer_deletion_succeeded: 'customer_deletion_succeeded',
  customer_update_succeeded: 'customer_update_succeeded',
  payment_added: 'payment_added',
  payment_removed: 'payment_removed',
  reduction_of_customer_credit: 'reduction_of_customer_credit',
  reduction_of_customer_credit_due_to_minimal_consumption: 'reduction_of_customer_credit_due_to_minimal_consumption',
  reduction_of_customer_expected_consumption: 'reduction_of_customer_expected_consumption',
  reduction_of_project_credit: 'reduction_of_project_credit',
  reduction_of_project_credit_due_to_minimal_consumption: 'reduction_of_project_credit_due_to_minimal_consumption',
  reduction_of_project_expected_consumption: 'reduction_of_project_expected_consumption',
  roll_back_customer_credit: 'roll_back_customer_credit',
  roll_back_project_credit: 'roll_back_project_credit',
  set_to_zero_overdue_credit: 'set_to_zero_overdue_credit',
  update_of_credit_by_staff: 'update_of_credit_by_staff',
  customer_permission_review_created: 'customer_permission_review_created',
  customer_permission_review_closed: 'customer_permission_review_closed',
} as const;

export const InvoicesEnum = {
  allowed_offerings_have_been_updated: 'allowed_offerings_have_been_updated',
  automatic_credit_adjustment: 'automatic_credit_adjustment',
  create_of_credit_by_staff: 'create_of_credit_by_staff',
  invoice_canceled: 'invoice_canceled',
  invoice_created: 'invoice_created',
  invoice_item_created: 'invoice_item_created',
  invoice_item_deleted: 'invoice_item_deleted',
  invoice_item_updated: 'invoice_item_updated',
  invoice_paid: 'invoice_paid',
  payment_created: 'payment_created',
  payment_removed: 'payment_removed',
  reduction_of_customer_credit: 'reduction_of_customer_credit',
  reduction_of_customer_credit_due_to_minimal_consumption: 'reduction_of_customer_credit_due_to_minimal_consumption',
  reduction_of_customer_expected_consumption: 'reduction_of_customer_expected_consumption',
  reduction_of_project_credit: 'reduction_of_project_credit',
  reduction_of_project_credit_due_to_minimal_consumption: 'reduction_of_project_credit_due_to_minimal_consumption',
  reduction_of_project_expected_consumption: 'reduction_of_project_expected_consumption',
  roll_back_customer_credit: 'roll_back_customer_credit',
  roll_back_project_credit: 'roll_back_project_credit',
  set_to_zero_overdue_credit: 'set_to_zero_overdue_credit',
  update_of_credit_by_staff: 'update_of_credit_by_staff',
} as const;

export const Offering_accountingEnum = {
  marketplace_offering_component_created: 'marketplace_offering_component_created',
  marketplace_offering_component_deleted: 'marketplace_offering_component_deleted',
  marketplace_offering_component_updated: 'marketplace_offering_component_updated',
  marketplace_plan_archived: 'marketplace_plan_archived',
  marketplace_plan_component_current_price_updated: 'marketplace_plan_component_current_price_updated',
  marketplace_plan_component_future_price_updated: 'marketplace_plan_component_future_price_updated',
  marketplace_plan_component_quota_updated: 'marketplace_plan_component_quota_updated',
  marketplace_plan_created: 'marketplace_plan_created',
  marketplace_plan_updated: 'marketplace_plan_updated',
  marketplace_plan_deleted: 'marketplace_plan_deleted',
} as const;

export const PermissionsEnum = {
  role_granted: 'role_granted',
  role_revoked: 'role_revoked',
  role_updated: 'role_updated',
} as const;

export const ProjectsEnum = {
  project_creation_succeeded: 'project_creation_succeeded',
  project_deletion_succeeded: 'project_deletion_succeeded',
  project_deletion_triggered: 'project_deletion_triggered',
  project_update_request_approved: 'project_update_request_approved',
  project_update_request_created: 'project_update_request_created',
  project_update_request_rejected: 'project_update_request_rejected',
  project_update_succeeded: 'project_update_succeeded',
  project_permission_review_created: 'project_permission_review_created',
  project_permission_review_closed: 'project_permission_review_closed',
} as const;

export const ProposalEnum = {
  proposal_canceled: 'proposal_canceled',
  proposal_document_added: 'proposal_document_added',
  proposal_document_removed: 'proposal_document_removed',
} as const;

export const ProvidersEnum = {
  marketplace_resource_create_canceled: 'marketplace_resource_create_canceled',
  marketplace_resource_create_failed: 'marketplace_resource_create_failed',
  marketplace_resource_create_requested: 'marketplace_resource_create_requested',
  marketplace_resource_create_succeeded: 'marketplace_resource_create_succeeded',
  marketplace_resource_terminate_failed: 'marketplace_resource_terminate_failed',
  marketplace_resource_terminate_requested: 'marketplace_resource_terminate_requested',
  marketplace_resource_terminate_succeeded: 'marketplace_resource_terminate_succeeded',
  marketplace_resource_update_failed: 'marketplace_resource_update_failed',
  marketplace_resource_update_limits_failed: 'marketplace_resource_update_limits_failed',
  marketplace_resource_update_limits_succeeded: 'marketplace_resource_update_limits_succeeded',
  marketplace_resource_update_requested: 'marketplace_resource_update_requested',
  resource_robot_account_created: 'resource_robot_account_created',
  resource_robot_account_deleted: 'resource_robot_account_deleted',
  resource_robot_account_state_changed: 'resource_robot_account_state_changed',
  resource_robot_account_updated: 'resource_robot_account_updated',
} as const;

export const ResourcesEnum = {
  marketplace_order_approved: 'marketplace_order_approved',
  marketplace_order_completed: 'marketplace_order_completed',
  marketplace_order_created: 'marketplace_order_created',
  marketplace_order_failed: 'marketplace_order_failed',
  marketplace_order_rejected: 'marketplace_order_rejected',
  marketplace_order_terminated: 'marketplace_order_terminated',
  marketplace_order_unlinked: 'marketplace_order_unlinked',
  marketplace_resource_create_canceled: 'marketplace_resource_create_canceled',
  marketplace_resource_create_failed: 'marketplace_resource_create_failed',
  marketplace_resource_create_requested: 'marketplace_resource_create_requested',
  marketplace_resource_create_succeeded: 'marketplace_resource_create_succeeded',
  marketplace_resource_downscaled: 'marketplace_resource_downscaled',
  marketplace_resource_erred_on_backend: 'marketplace_resource_erred_on_backend',
  marketplace_resource_paused: 'marketplace_resource_paused',
  marketplace_resource_terminate_canceled: 'marketplace_resource_terminate_canceled',
  marketplace_resource_terminate_failed: 'marketplace_resource_terminate_failed',
  marketplace_resource_terminate_requested: 'marketplace_resource_terminate_requested',
  marketplace_resource_terminate_succeeded: 'marketplace_resource_terminate_succeeded',
  marketplace_resource_unlinked: 'marketplace_resource_unlinked',
  marketplace_resource_update_canceled: 'marketplace_resource_update_canceled',
  marketplace_resource_update_end_date_succeeded: 'marketplace_resource_update_end_date_succeeded',
  marketplace_resource_update_failed: 'marketplace_resource_update_failed',
  marketplace_resource_update_limits_failed: 'marketplace_resource_update_limits_failed',
  marketplace_resource_update_limits_succeeded: 'marketplace_resource_update_limits_succeeded',
  marketplace_resource_update_requested: 'marketplace_resource_update_requested',
  marketplace_resource_update_succeeded: 'marketplace_resource_update_succeeded',
  openstack_floating_ip_attached: 'openstack_floating_ip_attached',
  openstack_floating_ip_connected: 'openstack_floating_ip_connected',
  openstack_floating_ip_description_updated: 'openstack_floating_ip_description_updated',
  openstack_floating_ip_detached: 'openstack_floating_ip_detached',
  openstack_floating_ip_disconnected: 'openstack_floating_ip_disconnected',
  openstack_network_cleaned: 'openstack_network_cleaned',
  openstack_network_created: 'openstack_network_created',
  openstack_network_deleted: 'openstack_network_deleted',
  openstack_network_imported: 'openstack_network_imported',
  openstack_network_pulled: 'openstack_network_pulled',
  openstack_network_updated: 'openstack_network_updated',
  openstack_port_cleaned: 'openstack_port_cleaned',
  openstack_port_created: 'openstack_port_created',
  openstack_port_deleted: 'openstack_port_deleted',
  openstack_port_imported: 'openstack_port_imported',
  openstack_port_pulled: 'openstack_port_pulled',
  openstack_port_updated: 'openstack_port_updated',
  openstack_router_updated: 'openstack_router_updated',
  openstack_security_group_cleaned: 'openstack_security_group_cleaned',
  openstack_security_group_created: 'openstack_security_group_created',
  openstack_security_group_deleted: 'openstack_security_group_deleted',
  openstack_security_group_imported: 'openstack_security_group_imported',
  openstack_security_group_pulled: 'openstack_security_group_pulled',
  openstack_security_group_rule_cleaned: 'openstack_security_group_rule_cleaned',
  openstack_security_group_rule_created: 'openstack_security_group_rule_created',
  openstack_security_group_rule_deleted: 'openstack_security_group_rule_deleted',
  openstack_security_group_rule_imported: 'openstack_security_group_rule_imported',
  openstack_security_group_rule_updated: 'openstack_security_group_rule_updated',
  openstack_security_group_updated: 'openstack_security_group_updated',
  openstack_server_group_cleaned: 'openstack_server_group_cleaned',
  openstack_server_group_created: 'openstack_server_group_created',
  openstack_server_group_deleted: 'openstack_server_group_deleted',
  openstack_server_group_imported: 'openstack_server_group_imported',
  openstack_server_group_pulled: 'openstack_server_group_pulled',
  openstack_subnet_cleaned: 'openstack_subnet_cleaned',
  openstack_subnet_created: 'openstack_subnet_created',
  openstack_subnet_deleted: 'openstack_subnet_deleted',
  openstack_subnet_imported: 'openstack_subnet_imported',
  openstack_subnet_pulled: 'openstack_subnet_pulled',
  openstack_subnet_updated: 'openstack_subnet_updated',
  openstack_tenant_quota_limit_updated: 'openstack_tenant_quota_limit_updated',
  resource_assign_floating_ip_failed: 'resource_assign_floating_ip_failed',
  resource_assign_floating_ip_scheduled: 'resource_assign_floating_ip_scheduled',
  resource_assign_floating_ip_succeeded: 'resource_assign_floating_ip_succeeded',
  resource_attach_failed: 'resource_attach_failed',
  resource_attach_scheduled: 'resource_attach_scheduled',
  resource_attach_succeeded: 'resource_attach_succeeded',
  resource_change_flavor_failed: 'resource_change_flavor_failed',
  resource_change_flavor_scheduled: 'resource_change_flavor_scheduled',
  resource_change_flavor_succeeded: 'resource_change_flavor_succeeded',
  resource_creation_failed: 'resource_creation_failed',
  resource_creation_scheduled: 'resource_creation_scheduled',
  resource_creation_succeeded: 'resource_creation_succeeded',
  resource_deletion_failed: 'resource_deletion_failed',
  resource_deletion_scheduled: 'resource_deletion_scheduled',
  resource_deletion_succeeded: 'resource_deletion_succeeded',
  resource_detach_failed: 'resource_detach_failed',
  resource_detach_scheduled: 'resource_detach_scheduled',
  resource_detach_succeeded: 'resource_detach_succeeded',
  resource_extend_failed: 'resource_extend_failed',
  resource_extend_scheduled: 'resource_extend_scheduled',
  resource_extend_succeeded: 'resource_extend_succeeded',
  resource_extend_volume_failed: 'resource_extend_volume_failed',
  resource_extend_volume_scheduled: 'resource_extend_volume_scheduled',
  resource_extend_volume_succeeded: 'resource_extend_volume_succeeded',
  resource_import_succeeded: 'resource_import_succeeded',
  resource_pull_failed: 'resource_pull_failed',
  resource_pull_scheduled: 'resource_pull_scheduled',
  resource_pull_succeeded: 'resource_pull_succeeded',
  resource_restart_failed: 'resource_restart_failed',
  resource_restart_scheduled: 'resource_restart_scheduled',
  resource_restart_succeeded: 'resource_restart_succeeded',
  resource_retype_failed: 'resource_retype_failed',
  resource_retype_scheduled: 'resource_retype_scheduled',
  resource_retype_succeeded: 'resource_retype_succeeded',
  resource_robot_account_created: 'resource_robot_account_created',
  resource_robot_account_deleted: 'resource_robot_account_deleted',
  resource_robot_account_state_changed: 'resource_robot_account_state_changed',
  resource_robot_account_updated: 'resource_robot_account_updated',
  resource_start_failed: 'resource_start_failed',
  resource_start_scheduled: 'resource_start_scheduled',
  resource_start_succeeded: 'resource_start_succeeded',
  resource_stop_failed: 'resource_stop_failed',
  resource_stop_scheduled: 'resource_stop_scheduled',
  resource_stop_succeeded: 'resource_stop_succeeded',
  resource_unassign_floating_ip_failed: 'resource_unassign_floating_ip_failed',
  resource_unassign_floating_ip_scheduled: 'resource_unassign_floating_ip_scheduled',
  resource_unassign_floating_ip_succeeded: 'resource_unassign_floating_ip_succeeded',
  resource_update_allowed_address_pairs_failed: 'resource_update_allowed_address_pairs_failed',
  resource_update_allowed_address_pairs_scheduled: 'resource_update_allowed_address_pairs_scheduled',
  resource_update_allowed_address_pairs_succeeded: 'resource_update_allowed_address_pairs_succeeded',
  resource_update_floating_ips_failed: 'resource_update_floating_ips_failed',
  resource_update_floating_ips_scheduled: 'resource_update_floating_ips_scheduled',
  resource_update_floating_ips_succeeded: 'resource_update_floating_ips_succeeded',
  resource_update_ports_failed: 'resource_update_ports_failed',
  resource_update_ports_scheduled: 'resource_update_ports_scheduled',
  resource_update_ports_succeeded: 'resource_update_ports_succeeded',
  resource_update_security_groups_failed: 'resource_update_security_groups_failed',
  resource_update_security_groups_scheduled: 'resource_update_security_groups_scheduled',
  resource_update_security_groups_succeeded: 'resource_update_security_groups_succeeded',
  resource_update_succeeded: 'resource_update_succeeded',
} as const;

export const ReviewEnum = {
  review_canceled: 'review_canceled',
} as const;

export const SshEnum = {
  ssh_key_creation_succeeded: 'ssh_key_creation_succeeded',
  ssh_key_deletion_succeeded: 'ssh_key_deletion_succeeded',
} as const;

export const SupportEnum = {
  attachment_created: 'attachment_created',
  attachment_deleted: 'attachment_deleted',
  attachment_updated: 'attachment_updated',
  issue_creation_succeeded: 'issue_creation_succeeded',
  issue_deletion_succeeded: 'issue_deletion_succeeded',
  issue_update_succeeded: 'issue_update_succeeded',
} as const;

export const UsersEnum = {
  auth_logged_in_with_saml2: 'auth_logged_in_with_saml2',
  auth_logged_out_with_saml2: 'auth_logged_out_with_saml2',
  freeipa_profile_created: 'freeipa_profile_created',
  freeipa_profile_deleted: 'freeipa_profile_deleted',
  freeipa_profile_disabled: 'freeipa_profile_disabled',
  freeipa_profile_enabled: 'freeipa_profile_enabled',
  marketplace_offering_user_created: 'marketplace_offering_user_created',
  marketplace_offering_user_deleted: 'marketplace_offering_user_deleted',
  marketplace_offering_user_restriction_updated: 'marketplace_offering_user_restriction_updated',
  ssh_key_creation_succeeded: 'ssh_key_creation_succeeded',
  ssh_key_deletion_succeeded: 'ssh_key_deletion_succeeded',
  user_activated: 'user_activated',
  user_creation_succeeded: 'user_creation_succeeded',
  user_deactivated: 'user_deactivated',
  user_deletion_succeeded: 'user_deletion_succeeded',
  user_details_update_succeeded: 'user_details_update_succeeded',
  user_has_been_created_by_staff: 'user_has_been_created_by_staff',
  user_password_updated: 'user_password_updated',
  user_password_updated_by_staff: 'user_password_updated_by_staff',
  user_update_succeeded: 'user_update_succeeded',
} as const;

export const Terms_of_serviceEnum = {
  terms_of_service_consent_granted: 'terms_of_service_consent_granted',
  terms_of_service_consent_revoked: 'terms_of_service_consent_revoked',
} as const;

// ===== PERMISSION ENUMS =====

export const RoleEnum = {
  CUSTOMER_OWNER: 'CUSTOMER.OWNER',
  CUSTOMER_SUPPORT: 'CUSTOMER.SUPPORT',
  CUSTOMER_MANAGER: 'CUSTOMER.MANAGER',
  PROJECT_ADMIN: 'PROJECT.ADMIN',
  PROJECT_MANAGER: 'PROJECT.MANAGER',
  PROJECT_MEMBER: 'PROJECT.MEMBER',
  OFFERING_MANAGER: 'OFFERING.MANAGER',
  CALL_REVIEWER: 'CALL.REVIEWER',
  CALL_MANAGER: 'CALL.MANAGER',
  PROPOSAL_MEMBER: 'PROPOSAL.MEMBER',
  PROPOSAL_MANAGER: 'PROPOSAL.MANAGER',
} as const;

export const PermissionEnum = {
  REGISTER_SERVICE_PROVIDER: 'SERVICE_PROVIDER.REGISTER',
  CREATE_OFFERING: 'OFFERING.CREATE',
  DELETE_OFFERING: 'OFFERING.DELETE',
  UPDATE_OFFERING_THUMBNAIL: 'OFFERING.UPDATE_THUMBNAIL',
  UPDATE_OFFERING: 'OFFERING.UPDATE',
  UPDATE_OFFERING_ATTRIBUTES: 'OFFERING.UPDATE_ATTRIBUTES',
  UPDATE_OFFERING_LOCATION: 'OFFERING.UPDATE_LOCATION',
  UPDATE_OFFERING_DESCRIPTION: 'OFFERING.UPDATE_DESCRIPTION',
  UPDATE_OFFERING_OPTIONS: 'OFFERING.UPDATE_OPTIONS',
  UPDATE_OFFERING_INTEGRATION: 'OFFERING.UPDATE_INTEGRATION',
  ADD_OFFERING_ENDPOINT: 'OFFERING.ADD_ENDPOINT',
  DELETE_OFFERING_ENDPOINT: 'OFFERING.DELETE_ENDPOINT',
  UPDATE_OFFERING_COMPONENTS: 'OFFERING.UPDATE_COMPONENTS',
  PAUSE_OFFERING: 'OFFERING.PAUSE',
  UNPAUSE_OFFERING: 'OFFERING.UNPAUSE',
  ARCHIVE_OFFERING: 'OFFERING.ARCHIVE',
  DRY_RUN_OFFERING_SCRIPT: 'OFFERING.DRY_RUN_SCRIPT',
  MANAGE_CAMPAIGN: 'OFFERING.MANAGE_CAMPAIGN',
  MANAGE_OFFERING_USER_GROUP: 'OFFERING.MANAGE_USER_GROUP',
  CREATE_OFFERING_PLAN: 'OFFERING.CREATE_PLAN',
  UPDATE_OFFERING_PLAN: 'OFFERING.UPDATE_PLAN',
  ARCHIVE_OFFERING_PLAN: 'OFFERING.ARCHIVE_PLAN',
  CREATE_OFFERING_SCREENSHOT: 'OFFERING.CREATE_SCREENSHOT',
  UPDATE_OFFERING_SCREENSHOT: 'OFFERING.UPDATE_SCREENSHOT',
  DELETE_OFFERING_SCREENSHOT: 'OFFERING.DELETE_SCREENSHOT',
  CREATE_OFFERING_USER: 'OFFERING.CREATE_USER',
  UPDATE_OFFERING_USER: 'OFFERING.UPDATE_USER',
  DELETE_OFFERING_USER: 'OFFERING.DELETE_USER',
  MANAGE_OFFERING_USER_ROLE: 'OFFERING.MANAGE_USER_ROLE',
  CREATE_RESOURCE_ROBOT_ACCOUNT: 'RESOURCE.CREATE_ROBOT_ACCOUNT',
  UPDATE_RESOURCE_ROBOT_ACCOUNT: 'RESOURCE.UPDATE_ROBOT_ACCOUNT',
  DELETE_RESOURCE_ROBOT_ACCOUNT: 'RESOURCE.DELETE_ROBOT_ACCOUNT',
  LIST_ORDERS: 'ORDER.LIST',
  APPROVE_PRIVATE_ORDER: 'ORDER.APPROVE_PRIVATE',
  APPROVE_ORDER: 'ORDER.APPROVE',
  REJECT_ORDER: 'ORDER.REJECT',
  DESTROY_ORDER: 'ORDER.DESTROY',
  CANCEL_ORDER: 'ORDER.CANCEL',
  LIST_RESOURCES: 'RESOURCE.LIST',
  UPDATE_RESOURCE: 'RESOURCE.UPDATE',
  TERMINATE_RESOURCE: 'RESOURCE.TERMINATE',
  LIST_IMPORTABLE_RESOURCES: 'RESOURCE.LIST_IMPORTABLE',
  SET_RESOURCE_END_DATE: 'RESOURCE.SET_END_DATE',
  SET_RESOURCE_USAGE: 'RESOURCE.SET_USAGE',
  SWITCH_RESOURCE_PLAN: 'RESOURCE.SET_PLAN',
  UPDATE_RESOURCE_LIMITS: 'RESOURCE.SET_LIMITS',
  SET_RESOURCE_BACKEND_ID: 'RESOURCE.SET_BACKEND_ID',
  SUBMIT_RESOURCE_REPORT: 'RESOURCE.SUBMIT_REPORT',
  SET_RESOURCE_BACKEND_METADATA: 'RESOURCE.SET_BACKEND_METADATA',
  SET_RESOURCE_STATE: 'RESOURCE.SET_STATE',
  UPDATE_RESOURCE_OPTIONS: 'RESOURCE.UPDATE_OPTIONS',
  ACCEPT_BOOKING_REQUEST: 'RESOURCE.ACCEPT_BOOKING_REQUEST',
  REJECT_BOOKING_REQUEST: 'RESOURCE.REJECT_BOOKING_REQUEST',
  MANAGE_RESOURCE_USERS: 'RESOURCE.MANAGE_USERS',
  RESOURCE_CONSUMPTION_LIMITATION: 'RESOURCE.CONSUMPTION_LIMITATION',
  MANAGE_OFFERING_BACKEND_RESOURCES: 'OFFERING.MANAGE_BACKEND_RESOURCES',
  GET_SERVICE_PROVIDER_API_SECRET_CODE: 'SERVICE_PROVIDER.GET_API_SECRET_CODE',
  GENERATE_SERVICE_PROVIDER_API_SECRET_CODE: 'SERVICE_PROVIDER.GENERATE_API_SECRET_CODE',
  LIST_SERVICE_PROVIDER_CUSTOMERS: 'SERVICE_PROVIDER.LIST_CUSTOMERS',
  LIST_SERVICE_PROVIDER_CUSTOMER_PROJECTS: 'SERVICE_PROVIDER.LIST_CUSTOMER_PROJECTS',
  LIST_SERVICE_PROVIDER_PROJECTS: 'SERVICE_PROVIDER.LIST_PROJECTS',
  LIST_SERVICE_PROVIDER_PROJECT_PERMISSIONS: 'SERVICE_PROVIDER.LIST_PROJECT_PERMISSIONS',
  LIST_SERVICE_PROVIDER_KEYS: 'SERVICE_PROVIDER.LIST_KEYS',
  LIST_SERVICE_PROVIDER_USERS: 'SERVICE_PROVIDER.LIST_USERS',
  LIST_SERVICE_PROVIDER_USER_CUSTOMERS: 'SERVICE_PROVIDER.LIST_USER_CUSTOMERS',
  LIST_SERVICE_PROVIDER_SERVICE_ACCOUNTS: 'SERVICE_PROVIDER.LIST_SERVICE_ACCOUNTS',
  LIST_SERVICE_PROVIDER_COURSE_ACCOUNTS: 'SERVICE_PROVIDER.LIST_COURSE_ACCOUNTS',
  SET_SERVICE_PROVIDER_OFFERINGS_USERNAME: 'SERVICE_PROVIDER.SET_OFFERINGS_USERNAME',
  GET_SERVICE_PROVIDER_STATISTICS: 'SERVICE_PROVIDER.GET_STATISTICS',
  GET_SERVICE_PROVIDER_REVENUE: 'SERVICE_PROVIDER.GET_REVENUE',
  GET_SERVICE_PROVIDER_ROBOT_ACCOUNT_CUSTOMERS: 'SERVICE_PROVIDER.GET_ROBOT_ACCOUNT_CUSTOMERS',
  GET_SERVICE_PROVIDER_ROBOT_ACCOUNT_PROJECTS: 'SERVICE_PROVIDER.GET_ROBOT_ACCOUNT_PROJECTS',
  CREATE_PROJECT_PERMISSION: 'PROJECT.CREATE_PERMISSION',
  CREATE_CUSTOMER_PERMISSION: 'CUSTOMER.CREATE_PERMISSION',
  CREATE_OFFERING_PERMISSION: 'OFFERING.CREATE_PERMISSION',
  CREATE_CALL_PERMISSION: 'CALL.CREATE_PERMISSION',
  MANAGE_PROPOSAL: 'PROPOSAL.MANAGE',
  MANAGE_PROPOSAL_REVIEW: 'PROPOSAL.MANAGE_REVIEW',
  UPDATE_PROJECT_PERMISSION: 'PROJECT.UPDATE_PERMISSION',
  UPDATE_CUSTOMER_PERMISSION: 'CUSTOMER.UPDATE_PERMISSION',
  UPDATE_OFFERING_PERMISSION: 'OFFERING.UPDATE_PERMISSION',
  UPDATE_CALL_PERMISSION: 'CALL.UPDATE_PERMISSION',
  UPDATE_PROPOSAL_PERMISSION: 'PROPOSAL.UPDATE_PERMISSION',
  DELETE_PROJECT_PERMISSION: 'PROJECT.DELETE_PERMISSION',
  DELETE_CUSTOMER_PERMISSION: 'CUSTOMER.DELETE_PERMISSION',
  DELETE_OFFERING_PERMISSION: 'OFFERING.DELETE_PERMISSION',
  DELETE_CALL_PERMISSION: 'CALL.DELETE_PERMISSION',
  DELETE_PROPOSAL_PERMISSION: 'PROPOSAL.DELETE_PERMISSION',
  CREATE_LEXIS_LINK: 'LEXIS_LINK.CREATE',
  DELETE_LEXIS_LINK: 'LEXIS_LINK.DELETE',
  LIST_PROJECTS: 'PROJECT.LIST',
  CREATE_PROJECT: 'PROJECT.CREATE',
  DELETE_PROJECT: 'PROJECT.DELETE',
  UPDATE_PROJECT: 'PROJECT.UPDATE',
  UPDATE_PROJECT_METADATA: 'PROJECT.UPDATE_METADATA',
  REVIEW_PROJECT_MEMBERSHIP: 'PROJECT.REVIEW_MEMBERSHIP',
  UPDATE_CUSTOMER: 'CUSTOMER.UPDATE',
  LIST_CUSTOMER_USERS: 'CUSTOMER.LIST_USERS',
  ACCEPT_REQUESTED_OFFERING: 'OFFERING.ACCEPT_CALL_REQUEST',
  APPROVE_AND_REJECT_PROPOSALS: 'CALL.APPROVE_AND_REJECT_PROPOSALS',
  CLOSE_ROUNDS: 'CALL.CLOSE_ROUNDS',
  CREATE_ACCESS_SUBNET: 'ACCESS_SUBNET.CREATE',
  UPDATE_ACCESS_SUBNET: 'ACCESS_SUBNET.UPDATE',
  DELETE_ACCESS_SUBNET: 'ACCESS_SUBNET.DELETE',
  UPDATE_OFFERING_USER_RESTRICTION: 'OFFERINGUSER.UPDATE_RESTRICTION',
  LIST_INVITATIONS: 'INVITATION.LIST',
  LIST_CUSTOMER_PERMISSION_REVIEWS: 'CUSTOMER.LIST_PERMISSION_REVIEWS',
  LIST_CALLS: 'CALL.LIST',
  CREATE_CALL: 'CALL.CREATE',
  UPDATE_CALL: 'CALL.UPDATE',
  LIST_ROUNDS: 'ROUND.LIST',
  LIST_PROPOSALS: 'PROPOSAL.LIST',
  MANAGE_SERVICE_ACCOUNT: 'SERVICE_ACCOUNT.MANAGE',
  MANAGE_COURSE_ACCOUNT: 'PROJECT.COURSE_ACCOUNT_MANAGE',
  SERVICE_PROVIDER_OPENSTACK_IMAGE_MANAGEMENT: 'SERVICE_PROVIDER.OPENSTACK_IMAGE_MANAGEMENT',
  HAS_OPENSTACK_INSTANCE_CONSOLE_ACCESS: 'OPENSTACK_INSTANCE.CONSOLE_ACCESS',
  CAN_MANAGE_OPENSTACK_INSTANCE_POWER: 'OPENSTACK_INSTANCE.MANAGE_POWER',
  CAN_MANAGE_OPENSTACK_INSTANCE: 'OPENSTACK_INSTANCE.MANAGE',
} as const;

// ===== FEATURE ENUMS =====

export const CustomerFeatures = {
  show_domain: 'customer.show_domain',
  payments_for_staff_only: 'customer.payments_for_staff_only',
  show_permission_reviews: 'customer.show_permission_reviews',
  show_banking_data: 'customer.show_banking_data',
} as const;

export const ProjectFeatures = {
  estimated_cost: 'project.estimated_cost',
  oecd_fos_2007_code: 'project.oecd_fos_2007_code',
  show_industry_flag: 'project.show_industry_flag',
  show_description_in_create_dialog: 'project.show_description_in_create_dialog',
  show_type_in_create_dialog: 'project.show_type_in_create_dialog',
  show_start_date_in_create_dialog: 'project.show_start_date_in_create_dialog',
  show_end_date_in_create_dialog: 'project.show_end_date_in_create_dialog',
  show_image_in_create_dialog: 'project.show_image_in_create_dialog',
  show_credit_in_create_dialog: 'project.show_credit_in_create_dialog',
  mandatory_start_date: 'project.mandatory_start_date',
  mandatory_end_date: 'project.mandatory_end_date',
  show_permission_reviews: 'project.show_permission_reviews',
  show_kind_in_create_dialog: 'project.show_kind_in_create_dialog',
} as const;

export const UserFeatures = {
  preferred_language: 'user.preferred_language',
  ssh_keys: 'user.ssh_keys',
  notifications: 'user.notifications',
  disable_user_termination: 'user.disable_user_termination',
  show_slug: 'user.show_slug',
  show_username: 'user.show_username',
} as const;

export const MarketplaceFeatures = {
  import_resources: 'marketplace.import_resources',
  conceal_prices: 'marketplace.conceal_prices',
  show_experimental_ui_components: 'marketplace.show_experimental_ui_components',
  show_call_management_functionality: 'marketplace.show_call_management_functionality',
  lexis_links: 'marketplace.lexis_links',
  catalogue_only: 'marketplace.catalogue_only',
  call_only: 'marketplace.call_only',
  show_resource_end_date: 'marketplace.show_resource_end_date',
  allow_display_of_images_in_markdown: 'marketplace.allow_display_of_images_in_markdown',
  display_user_tos: 'marketplace.display_user_tos',
  display_software_catalog: 'marketplace.display_software_catalog',
  display_offering_partitions: 'marketplace.display_offering_partitions',
} as const;

export const SupportFeatures = {
  pricelist: 'support.pricelist',
  vm_type_overview: 'support.vm_type_overview',
  conceal_change_request: 'support.conceal_change_request',
} as const;

export const InvitationsFeatures = {
  conceal_civil_number: 'invitations.conceal_civil_number',
  civil_number_required: 'invitations.civil_number_required',
  show_service_accounts: 'invitations.show_service_accounts',
  show_course_accounts: 'invitations.show_course_accounts',
} as const;

export const RancherFeatures = {
  volume_mount_point: 'rancher.volume_mount_point',
  apps: 'rancher.apps',
} as const;

export const SlurmFeatures = {
  jobs: 'slurm.jobs',
} as const;

export const OpenstackFeatures = {
  hide_volume_type_selector: 'openstack.hide_volume_type_selector',
  show_migrations: 'openstack.show_migrations',
} as const;

export const DeploymentFeatures = {
  send_metrics: 'deployment.send_metrics',
  enable_cookie_notice: 'deployment.enable_cookie_notice',
} as const;


// ===== TYPE DEFINITIONS =====

export type EventEnumType = typeof AuthEnum | typeof ProposalEnum | typeof UsersEnum;
export type PermissionEnumType = typeof RoleEnum | typeof PermissionEnum;
export type FeatureEnumType = typeof CustomerFeatures | typeof MarketplaceFeatures;

// Helper functions
export const getEventGroupKeys = () => Object.keys({
  access_subnets: Access_subnetsEnum,
  auth: AuthEnum,
  call: CallEnum,
  credits: CreditsEnum,
  customers: CustomersEnum,
  invoices: InvoicesEnum,
  offering_accounting: Offering_accountingEnum,
  permissions: PermissionsEnum,
  projects: ProjectsEnum,
  proposal: ProposalEnum,
  providers: ProvidersEnum,
  resources: ResourcesEnum,
  review: ReviewEnum,
  ssh: SshEnum,
  support: SupportEnum,
  users: UsersEnum,
  terms_of_service: Terms_of_serviceEnum,
});

export const isValidEventGroup = (group: string): boolean => {
  return getEventGroupKeys().includes(group);
};
